=== Hathor86/oskd/OnScreenKeyboardDisplay/bin/x86/Debug/Configuration/LayoutSchema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="http://www.w3schools.com"
           xmlns="http://www.w3schools.com"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
  <!--Attributes-->
  <xs:attribute name="AxisRef">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="X" />
        <xs:enumeration value="Y" />
      </xs:restriction>
    </xs:simpleType>
  </xs:attribute>

  <!--Elements-->
  <xs:element name="Value">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Esc" />

        <xs:enumeration value="F1" />
        <xs:enumeration value="F2" />
        <xs:enumeration value="F3" />
        <xs:enumeration value="F4" />

        <xs:enumeration value="F5" />
        <xs:enumeration value="F6" />
        <xs:enumeration value="F7" />
        <xs:enumeration value="F8" />

        <xs:enumeration value="F9" />
        <xs:enumeration value="F10" />
        <xs:enumeration value="F11" />
        <xs:enumeration value="F12" />

        <xs:enumeration value="Tilde" />
        <xs:enumeration value="1" />
        <xs:enumeration value="2" />
        <xs:enumeration value="3" />
        <xs:enumeration value="4" />
        <xs:enumeration value="5" />
        <xs:enumeration value="6" />
        <xs:enumeration value="7" />
        <xs:enumeration value="8" />
        <xs:enumeration value="9" />
        <xs:enumeration value="0" />
        <xs:enumeration value="Minus" />
        <xs:enumeration value="Plus" />
        <xs:enumeration value="Backspace" />

        <xs:enumeration value="Tab" />
        <xs:enumeration value="Q" />
        <xs:enumeration value="W" />
        <xs:enumeration value="E" />
        <xs:enumeration value="R" />
        <xs:enumeration value="T" />
        <xs:enumeration value="Y" />
        <xs:enumeration value="U" />
        <xs:enumeration value="I" />
        <xs:enumeration value="O" />
        <xs:enumeration value="P" />
        <xs:enumeration value="OpenBracket" />
        <xs:enumeration value="CloseBracket" />
        <xs:enumeration value="Backslash" />

        <xs:enumeration value="CapsLock" />
        <xs:enumeration value="A" />
        <xs:enumeration value="S" />
        <xs:enumeration value="D" />
        <xs:enumeration value="F" />
        <xs:enumeration value="G" />
        <xs:enumeration value="H" />
        <xs:enumeration value="J" />
        <xs:enumeration value="K" />
        <xs:enumeration value="L" />
        <xs:enumeration value="Semicolon" />
        <xs:enumeration value="Quotes" />
        <xs:enumeration value="Enter" />

        <xs:enumeration value="LeftShift" />
        <xs:enumeration value="Z" />
        <xs:enumeration value="X" />
        <xs:enumeration value="C" />
        <xs:enumeration value="V" />
        <xs:enumeration value="B" />
        <xs:enumeration value="N" />
        <xs:enumeration value="M" />
        <xs:enumeration value="Comma" />
        <xs:enumeration value="Period" />
        <xs:enumeration value="Question" />
        <xs:enumeration value="RightShift" />

        <xs:enumeration value="LeftControl" />
        <xs:enumeration value="LeftWindows" />
        <xs:enumeration value="LeftAlt" />
        <xs:enumeration value="Spacebar" />
        <xs:enumeration value="RightAlt" />
        <xs:enumeration value="RightWindows" />
        <xs:enumeration value="Menu" />
        <xs:enumeration value="RightControl" />

        <xs:enumeration value="PrintScreen" />
        <xs:enumeration value="ScrollLock" />
        <xs:enumeration value="Pause" />
        <xs:enumeration value="Insert" />
        <xs:enumeration value="Home" />
        <xs:enumeration value="PageUp" />
        <xs:enumeration value="Delete" />
        <xs:enumeration value="End" />
        <xs:enumeration value="PageDown" />

        <xs:enumeration value="Up" />
        <xs:enumeration value="Left" />
        <xs:enumeration value="Down" />
        <xs:enumeration value="Right" />

        <xs:enumeration value="NumLockLight" />
        <xs:enumeration value="CapsLockLight" />
        <xs:enumeration value="ScrollLockLight" />

        <xs:enumeration value="NumLock" />
        <xs:enumeration value="Divide" />
        <xs:enumeration value="Multiply" />
        <xs:enumeration value="Substract" />
        <xs:enumeration value="Numpad7" />
        <xs:enumeration value="Numpad8" />
        <xs:enumeration value="Numpad9" />
        <xs:enumeration value="Numpad4" />
        <xs:enumeration value="Numpad5" />
        <xs:enumeration value="Numpad6" />
        <xs:enumeration value="Add" />
        <xs:enumeration value="Numpad1" />
        <xs:enumeration value="Numpad2" />
        <xs:enumeration value="Numpad3" />
        <xs:enumeration value="Numpad0" />
        <xs:enumeration value="Decimal" />
        <xs:enumeration value="NumpadEnter" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="ButtonType">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <xs:enumeration value="Square" />
        <xs:enumeration value="Rectangle24" />
        <xs:enumeration value="Rectangle30" />
        <xs:enumeration value="Rectangle36" />
        <xs:enumeration value="Rectangle43" />
        <xs:enumeration value="Rectangle48" />
        <xs:enumeration value="Rectangle123" />
        <xs:enumeration value="VerticalRectangle" />
      </xs:restriction>
    </xs:simpleType>
  </xs:element>

  <xs:element name="PositionType">
    <xs:complexType>
      <xs:simpleContent>        
        <xs:extension base="xs:string">          
          <xs:attribute ref="AxisRef">
          </xs:attribute>
        </xs:extension>
      </xs:simpleContent>
    </xs:complexType>
  </xs:element>

  <xs:element name="X">
    <xs:simpleType>
      <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>
  </xs:element>

  <xs:element name="Y">
    <xs:simpleType>
      <xs:restriction base="xs:positiveInteger" />
    </xs:simpleType>
  </xs:element>

  <xs:element name="Key">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="Value" />
        <xs:element ref="ButtonType" />
        <xs:element ref="PositionType" />
        <xs:element ref="X" minOccurs="0" />
        <xs:element ref="Y" minOccurs="0" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>


  <!--Document-->
  <xs:element name="Layout">
    <xs:complexType>
      <xs:sequence maxOccurs="unbounded">
        <xs:element ref="Key" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Hathor86/oskd/OnScreenKeyboardDisplayLibrary/Configuration/BaseLayout.xml
<?xml version="1.0" encoding="utf-8" ?>
<Layout xmlns="http://www.w3schools.com"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation=" http://www.w3schools.com LayoutSchema.xsd"
        xmlns:custom="http://www.w3schools.com"
        >
  <!--1st row => Esc-F12-->
  <Key>
    <Value>Esc</Value>
    <ButtonType>Square</ButtonType>
    <PositionType>Absolute</PositionType>
    <X>6</X>
    <Y>2</Y>
  </Key>

  <Key>
    <Value>F1</Value>
    <ButtonType>Square</ButtonType>
    <PositionType>Absolute</PositionType>
    <X>36</X>
    <Y>2</Y>
  </Key>
  <Key>
    <Value>F2</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>F3</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>F4</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>

  <Key>
    <Value>F5</Value>
    <ButtonType>Square</ButtonType>
    <PositionType>Absolute</PositionType>
    <X>126</X>
    <Y>2</Y>
  </Key>
  <Key>
    <Value>F6</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>F7</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>F8</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>

  <Key>
    <Value>F9</Value>
    <ButtonType>Square</ButtonType>
    <PositionType>Absolute</PositionType>
    <X>217</X>
    <Y>2</Y>
  </Key>
  <Key>
    <Value>F10</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>F11</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>F12</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>

  <!--2nd row => Top row numbers-->
  <Key>
    <Value>Tilde</Value>
    <ButtonType>Square</ButtonType>
    <PositionType>Absolute</PositionType>
    <X>6</X>
    <Y>23</Y>
  </Key>
  <Key>
    <Value>1</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>2</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>3</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>4</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>5</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>6</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>7</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>8</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>9</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>0</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>Minus</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>Plus</Value>
    <ButtonType>Square</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>Backspace</Value>
    <ButtonType>Rectangle30</ButtonType>
    <PositionType custom:AxisRef="X">Relative</PositionType>
  </Key>

  <!--3rd row => Tab-Baclslash-->
  <Key>
    <Value>Tab</Value>
    <ButtonType>Rectangle30</ButtonType>
    <PositionType>Absolute</PositionType>
    <X>6</X>
    <Y>42</Y>
  </Key>
  <Key>
    <Value>Q</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>W</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>E</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>R</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>T</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>Y</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>U</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>I</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>O</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>P</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>OpenBracket</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>CloseBracket</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>
  <Key>
    <Value>Backslash</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>
  </Key>

  <!--4th row => Caps Lock -> Enter-->
  <Key>
    <Value>CapsLock</Value>
    <ButtonType>Rectangle36</ButtonType>
    <PositionType>Absolute</PositionType>
    <X>6</X>
    <Y>61</Y>
  </Key>
  <Key>
    <Value>A</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>S</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>D</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>F</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>G</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>H</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>J</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>K</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>L</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>Semicolon</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>Quotes</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>Enter</Value>
    <ButtonType>Rectangle36</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>

  <!--5th row => Shift-Shift-->
  <Key>
    <Value>LeftShift</Value>
    <ButtonType>Rectangle43</ButtonType>
    <PositionType>Absolute</PositionType>
    <X>6</X>
    <Y>80</Y>
  </Key>
  <Key>
    <Value>Z</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>X</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>C</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>V</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>B</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>N</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>M</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>Comma</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>Period</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>Question</Value>
    <ButtonType>Square</ButtonType>
    <PositionType  custom:AxisRef="X">Relative</PositionType>    
  </Key>
  <Key>
    <Value>RightShift</Value>
